travis:
  secure:
    BINSTAR_TOKEN: q3wZNeG3cg0Eo5SfoOonR7nLU7/x5bEjajHMNDueL+Eg3yYHVRqIm3/0eafgmQSXe/7+cMTdMOe1Un7du5QsoNATDWGKKwYo0SN01WJ0IObsuHghttXdbRGzI5RABK5UbE3z+EIaVQXOFFVtMgCJfIoOAEn5amI9oFxGpzpaWBPp5zAyLxmVPf1TAxqsXAthbAjeFdbGGAnITuxSzdAytiqef0a7p35Fj45IjuSwKQO8nfkM2x83LWOzT16HCGZnm6cDLz6npoq2sfDS3wsQWMBE/YquuP+0vTNoUCDmQuW9aDzXv5fqIaAwTvklVn46VnS8pzlMTALnRJm7n5ZDv0YoP+cshCTAGLJQ4qKzBei5IUtQVPp/3NSSWn2zSYP8ZMxRZ7n6RblxjxD2ArRmqWGH/zuueK2sQXEnmmPx6r4GXqnYxPWRIUMqh3lksRYQoX/kPts7VqIYk1j4zVHfIE/FdDg/g+soBwX2lBfrnksJ5rdKTNPcpl1dUKOP3GjxJCXVi0HPsVYmtclxnv/BeP8wrZTptajonJDHrWM8pwHiqBy4vB49NnsK8gUy8sD2hzM5BSl2Z/Wct93qi2D8lfFT2hUiwZclslSYwKDKyLblntQZpGOgF2emwZob5mjEdxFcnvYtJ3AZur2DWwjEQMQXg0bxFWSYesmPheDmeWc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
